"""
Django settings for opack_project project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see:
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Chemin de base du projet
BASE_DIR = Path(__file__).resolve().parent.parent

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = 'core.User'

# Backends d'authentification (e-mail personnalisé + backend par défaut)
AUTHENTICATION_BACKENDS = [
    'core.utils.EmailBackend',  # Authentification via e-mail
    'django.contrib.auth.backends.ModelBackend',  # Backend Django par défaut
]

# Clé secrète pour le chiffrement
SECRET_KEY = 'django-insecure-r!1hp)ghdbeu5fd-($2t)o+m7nm65fj^8phz5%1wr517=e6nsg'

# Mode debug - Ne pas activer en production !
DEBUG = True

# Hôtes autorisés
ALLOWED_HOSTS = ['13.61.80.136', '127.0.0.1', 'localhost']

# Applications installées
INSTALLED_APPS = [
    'import_export',  # Gestion des imports/exports de données
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # Application principale
]

# Middleware - Gestion des requêtes/réponses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.save_last_url.SaveLastVisitedURLMiddleware',  # Middleware personnalisé
]

# Configuration des URLs
ROOT_URLCONF = 'opack_project.urls'

# Configuration des templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'],  # Chemin vers les templates
        'APP_DIRS': True,  # Recherche automatique dans les applications
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Application WSGI
WSGI_APPLICATION = 'opack_project.wsgi.application'

# Base de données - PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'djangoopack',
        'USER': 'postgres',
        'PASSWORD': '1jourjesuistomber!',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Validation des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Redirections par défaut après connexion/déconnexion
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Paramètres de localisation
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')


# Configuration des fichiers médias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#SITE_URL = "http://myipadress:8000"
# Fichiers statiques et médias
# STATIC_URL = 'static/'
# STATICFILES_DIRS = ["/Users/william/Downloads/AppOpack-main/Opack_Git/static"]
# STATIC_ROOT = "/Users/william/Downloads/AppOpack-main/Opack_Git/staticfiles"
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'ERROR',  # Affiche uniquement les erreurs
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Import-export : transactions automatiques pour éviter les incohérences
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Configuration SMTP pour l'envoi des e-mails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # TLS
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'opackbordeaux@gmail.com'
EMAIL_HOST_PASSWORD = 'trbr uope owzb oole'  # Mot de passe d'application Google
DEFAULT_FROM_EMAIL = 'Opack <opackbordeaux@gmail.com>'

# Paramètres par défaut pour les clés primaires
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Désactivation du cache pour le développement
#CACHE_MIDDLEWARE_SECONDS = 0
#CACHE_MIDDLEWARE_ALIAS = 'default'
