# Generated by Django 4.2.16 on 2024-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_date_derniere_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Colis validé'),
        ),
    ]
