# Generated by Django 4.2.16 on 2024-12-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_validated_colis_est_valide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colis',
            old_name='est_valide',
            new_name='is_validated',
        ),
    ]
