# Generated by Django 4.2.16 on 2024-12-10 15:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_colis_status_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='id',
            field=models.CharField(default=core.models.generate_short_id, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colis',
            name='status_retour',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validé', 'Validé'), ('aucun', 'Aucun')], default='aucun', max_length=20),
        ),
        migrations.AlterField(
            model_name='profil',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score utilisateur'),
        ),
    ]
